FROM node:12
COPY . /
RUN cp /app/sources.list /etc/apt/&& ls &&apt update && apt install -y libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2

WORKDIR /app
RUN npm install && ls
CMD ["npm","start"]
